### ISSUE TITLE
  今天登陆报错，错误如下

### ISSUE THREAD

**Issue by lu9999** [harryhare/1point3acres#15]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1386, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 312, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 281, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by harryhare** [comment]
可能是被墙了

**Comment by harryhare** [comment]
主要可以关掉翻墙软件，然后试下网页是否能直接打卡。
现在的代码，一是没有解决cloudflare的五秒盾，可能有奇怪的错误，二是一亩三分地有时会被墙会导致报链接错误

**Comment by lu9999** [comment]
我在US啊，没有翻墙啊，10次有9次都是这个问题，之前几天一直很稳定，我试了去地上登陆没有问题，有办法解决吗？

**Comment by harryhare** [comment]
那就好奇怪。。。远程连接关闭一般都是网络问题。。。主要我这边还没法复现

**Comment by lu9999** [comment]
我是3个账号放一起，好像一个账号一个账号跑不会出问题

**Comment by harryhare** [comment]
我两个账号，还没遇到过，要不加个长点的sleep试试？

**Comment by lu9999** [comment]
嗯，我在账号于账号之间放了60s sleep，现在好像可以了，先试了30s不行。估计现在还管登陆太快了。。

**Comment by lu9999** [comment]
另外贡献3个题目
'下面论坛规则，下面哪种说法是正确的？':'有的版块发帖消耗积分。如果试图跨区发帖躲开限制，在帖子被挪到正确的版块后，仍可能会被扣分。',
'Disagree agreeably 是什么意思？':'这些都包括。',
'谈判工资时，哪种做法有利于得到更大的包裹？':'精读工资谈判宝典：https://www.1point3acres.com/bbs/thread-286214-1-1.html 知己知彼，百战不殆',

**Comment by Change72** [comment]
我帐号之间是 10*60s 的 sleep，今天也好几次遇到了这个错误，我感觉是验证码的时间过久，导致登陆的connection 被abort

**Comment by Change72** [comment]
首个账号可以，第二个号怎么试都不行了

**Comment by Change72** [comment]
折腾了一个小时发现，现在怎么好像是在封ip吗？两台不同电脑的ip都是，首个没问题，第二个开始，就完全不行。最后发现浏览器都访问不了一亩三分地了
