### ISSUE TITLE
Running script failed

### ISSUE THREAD

**Issue by PeppaCat** [harryhare/1point3acres#2]
Hi, I followed the setting procedure, but when manually testing the action, it failed on the "run the script" step, the error message is as follows:
```
1s
Run cd src && python3 service.py ""
  cd src && python3 service.py ""
  shell: /usr/bin/bash -e {0}
Traceback (most recent call last):
  File "service.py", line 91, in <module>
    main()
  File "service.py", line 83, in main
    users = json.loads(sys.argv[1].replace("'", '"'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.
```

**Comment by harryhare** [comment]
Do you configure repo secret mentioned in the second step of readme ?

**Comment by PeppaCat** [comment]
I checked that procedure again and found that I did not setting the repo secret name correctly to "USERS", and it worked after fixing the name. Sorry to bother you and thanks for the great tool!
