### ISSUE TITLE
2captcha超时

### ISSUE THREAD

**Issue by unemployed-denizen** [harryhare/1point3acres#44]
调用以下代码的时候会卡住，一直超时：
raw_requests.py", line 290,
result = solver.turnstile(sitekey=cf_capcha_site_key, url=checkin_page, useragent=user_agent)

2captcha网站显示`ERROR_CAPTCHA_UNSOLVABLE`
![image](https://github.com/harryhare/1point3acres/assets/63128680/4eda2c8b-1b95-4fec-9320-556c8144f52f)

最近才出现这种情况，以前没有。请问怎么解决呢？谢谢

完整报错
```
Traceback (most recent call last):
  File "D:/PycharmProjects/1point3acres/src/service.py", line 111, in <module>
    main()
  File "D:/PycharmProjects/1point3acres/src/service.py", line 97, in main
    do_all_cookie(solver, user["cookie"])
  File "D:/PycharmProjects/1point3acres/src/service.py", line 70, in do_all_cookie
    do_daily_checkin2_(solver)
  File "D:\PycharmProjects\1point3acres\src\raw_requests.py", line 290, in do_daily_checkin2_
    result = solver.turnstile(sitekey=cf_capcha_site_key, url=checkin_page, useragent=user_agent)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\twocaptcha\solver.py", line 446, in turnstile
    **kwargs)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\twocaptcha\solver.py", line 500, in solve
    code = self.wait_result(id_, timeout, sleep)
  File "xxx\AppData\Local\Programs\Python\Python37\lib\site-packages\twocaptcha\solver.py", line 518, in wait_result
    raise TimeoutException(f'timeout {timeout} exceeded')
twocaptcha.solver.TimeoutException: timeout 120.0 exceeded
```

**Comment by harryhare** [comment]
好像因为验证码的形式改了，我看下怎么解

**Comment by lu9999** [comment]
我也遇到同样的问题
```shell
Traceback (most recent call last):
  File "service.py", line 111, in <module>
    main()
  File "service.py", line 97, in main
    do_all_cookie(solver, user["cookie"])
  File "service.py", line 70, in do_all_cookie
    do_daily_checkin2_(solver)
  File "/volume3/homes/xxx/1point3acres/src/raw_requests.py", line 282, in do_daily_checkin2_
    result = solver.turnstile(sitekey=cf_capcha_site_key, url=checkin_page, useragent=user_agent)
  File "/var/services/homes/xxx/.local/lib/python3.8/site-packages/twocaptcha/solver.py", line 443, in turnstile
    result = self.solve(sitekey=sitekey,
  File "/var/services/homes/xxx/.local/lib/python3.8/site-packages/twocaptcha/solver.py", line 500, in solve
    code = self.wait_result(id_, timeout, sleep)
  File "/var/services/homes/xxx/.local/lib/python3.8/site-packages/twocaptcha/solver.py", line 518, in wait_result
    raise TimeoutException(f'timeout {timeout} exceeded')
twocaptcha.solver.TimeoutException: timeout 120.0 exceeded
```

**Comment by bingyu50** [comment]
有解决方案了么？

**Comment by harryhare** [comment]
完蛋，没法复现。如果是timeout 的话，感觉可以加个重试逻辑，以后加

**Comment by timerring** [comment]
现在应该换回 [`cloudflare turnstile`](https://www.cloudflare.com/zh-cn/application-services/products/turnstile/) 了
